apiVersion: v1
kind: ReplicationController
metadata:
  name: echo-server-rc
  namespace: training
spec:
  replicas: 5
  selector:
    app-name: "echo-server"
  template:
    metadata:
      namespace: training
      labels:
        app-name: "echo-server"
    spec:
      containers:
        - name: echo-server
          image: landrzejewski/echo-server
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "64M"
              cpu: "250m"
            limits:
              memory: "128M"
              cpu: "500m"