apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  namespace: training
  labels:
    app-name: "echo-server"
    env: "dev"
spec:
  # nodeName: node1
  nodeSelector:
    type: local
  containers:
    - name: echo-server
      image: landrzejewski/echo-server:v1
      ports:
        - containerPort: 8080
          name: http
      resources:
        requests:
          memory: "64M"
          cpu: "250m"
        limits:
          memory: "128M"
          cpu: "500m"