apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  namespace: training
  labels:
    app-name: "echo-server"
    env: "dev"
  annotations:
    build-version: "42"
    git-commit: "a1b2c3d4"
    changelog-url: "https://git.example.com/myrepo/commit/a1b2c3d4"
    maintainer: "ops-team@example.com"
spec:
  containers:
    - name: echo-server
      image: landrzejewski/echo-server:v1  #landrzejewski/echo-server-unhealthy:v1
      ports:
        - containerPort: 8080
          name: http
      # restartPolicy: Always    # default
      resources:
        requests:
          memory: "64M"
          cpu: "250m"
        limits:
          memory: "128M"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 30
        timeoutSeconds: 2
        periodSeconds: 3
        failureThreshold: 3
      readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 2
          successThreshold: 1