apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  labels:
    test: "true"
spec:
  containers:
    - name: echo-server
      image: landrzejewski/echo-server:v1
      ports:
        - containerPort: 8080
          name: http