apiVersion: v1
kind: Service
metadata:
  name: echo-server-svc
spec:
  selector:
    app-name: "echo-server"
  # clusterIP: 17.122.11.122
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
    - port: 80
      targetPort: http #8080
      nodePort: 30000