apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sqrt-hpa
  namespace: training
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    kind: Deployment
    name: sqrt-dep
    apiVersion: apps/v1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50