apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-dep
  namespace: training
  annotations:
    kubernetes.io/change-cause: "initial release"
spec:
  replicas: 5
  selector:
    matchLabels:
      app-name: "echo-server"
#    matchExpressions:
#      - key: app-name
#        values:
#          - echo-server
#          - echo
#        operator: In
  template:
    metadata:
      namespace: training
      labels:
        app-name: "echo-server"
    spec:
      containers:
        - name: echo-server
          image: landrzejewski/echo-server:v1
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "64M"
              cpu: "250m"
            limits:
              memory: "128M"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            successThreshold: 1