apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  namespace: training
spec:
  hostPath:
    path: /tmp/storage
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  #volumeMode: Block