apiVersion: apps/v1
kind: Deployment
metadata:
  name: updater-dep
  namespace: training
  annotations:
    kubernetes.io/change-cause: "initial release"
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: "updater"
  template:
    metadata:
      namespace: training
      labels:
        app-name: "updater"
    spec:
      containers:
        - name: nginx
          image: klasawchmurze.pl:5000/docker.io/nginx:1.21-alpine
          ports:
            - containerPort: 80
          volumeMounts:
              - name: storage
                mountPath: /usr/share/nginx/html

        - name: updater
          #command:
          #  - /update.sh

          #image: klasawchmurze.pl:5000/docker.io/landrzejewski/updater:v1
          #args:
          #  - "20"
          image: klasawchmurze.pl:5000/docker.io/landrzejewski/updater:v2
          #env:
          #  - name: INTERVAL
          #    value: "20"

          #env:
          #  - name: INTERVAL
          #    valueFrom:
          #      configMapKeyRef:
          #        name: updater-cm
          #        key: INTERVAL

          envFrom:
            - configMapRef:
                name: updater-cm
            - secretRef:
                name: db-credentials

          volumeMounts:
              - name: storage
                mountPath: /var/htdocs
              - name: config
                mountPath: /config

      volumes:
        - name: storage
          #emptyDir: {}

          #emptyDir:
          #  medium: Memory

          #hostPath:
          #  path: /tmp/updater

          persistentVolumeClaim:
            claimName: storage-pvc

        - name: config
          configMap:
            name: updater-cm
